apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codigo-observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: k8s/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codigo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: k8s/apps/codigo
  destination:
    server: https://kubernetes.default.svc
    namespace: codigo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
